---
title: "In-class Exercise 04"
author: "Ten Wei Peng"
date: "May 04, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

## Getting Started

## Installing and loading the required libraries

```{r}
pacman::p_load(ggstatsplot, tidyverse)

```

### Data import

For the purpose of this exercise, *Exam_data.csv* will be used.

```{r}
exam <- read_csv("data/Exam_data.csv")
```

#### Parametric
```{r}
set.seed(1234)

p <- gghistostats(
  data = exam,
  x = ENGLISH,
  type = "parametric",
  test.value = 60,
  bin.args =list(color ="black",
                 fill = "grey50",
                 alpha = 0.7),
  normal.curve = FALSE,
  normal.curve.args = list(linewidth =2),
  xlab = "English scores"
)

p
```


```{r}
extract_stats(p)
```

#### Bayes
```{r}
set.seed(1234)

gghistostats(
  data = exam,
  x = ENGLISH,
  type = "bayes",
  test.value = 60,
  bin.args =list(color ="black",
                 fill = "grey50",
                 alpha = 0.7),
  normal.curve = TRUE,
  normal.curve.args = list(linewidth =2),
  xlab = "English scores"
)

```




```{r}
ggdotplotstats(
  data = exam,
  x= ENGLISH,
  y= CLASS,
  title = "",
  xlab = ""
)
```



```{r}
#### data preparation step for visualization using pivot_longer
exam_long <- exam %>%
  pivot_longer(
    cols = ENGLISH:SCIENCE,
    names_to = "SUBJECT",
    values_to = "SCORES") %>%
  filter(CLASS == "3A")
  

#### visualization after pivoting
ggwithinstats(
  data    = filter(exam_long,
                   SUBJECT %in%
                     c("MATHS", "SCIENCE")),
  x= SUBJECT,
  y= SCORES,
  type = "p"
)

```



```{r}
ggscatterstats(
  data = exam,
  x = MATHS,
  y = ENGLISH,
  marginal = TRUE,
  label.var = ID,
  label.expression = ENGLISH > 90 & MATHS > 90
)
```

## Funnel Plots

Next, we explore Funnel Plots


```{r}

```















