---
title: "In-class Exercise 09: "
author: "Ten Wei Peng"
date: "June 15, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---


```{r}
pacman::p_load(scatterPlotMatrix, parallelPlot, cluster, factoextra, tidyverse)
```


## Importing Data

First, let us import the data into R by using *read_csv()* of **readr** package.

```{r}
wine <- read_csv("data/wine_quality.csv")
```

```{r}
ggplot(data=wine,
        aes(x=type))+
  geom_bar()
```

```{r}
whitewine <- wine %>%
  filter(type == "white") %>%
  select(c(1:11))
```



```{r}
scatterPlotMatrix(whitewine,
                  corrPlotType = "Text",
                  distribType = 1,
                  width = 500,
                  height = 500)
```








```{r}
set.seed(123)
kmeans4 <- kmeans(whitewine, 4, nstart=25)
print(kmeans4)

```

```{r}
fviz_cluster(kmeans4, data =whitewine)

```



```{r}
whitewine <- whitewine %>%
  mutate(Cluster = kmeans4$cluster)
```



```{r}
whitewine$Cluster <-
  as_factor(whitewine$Cluster)
```

```{r}
#| fig-width: 12
#| fig-height: 6
histoVisibility <- rep(TRUE, ncol(whitewine))
parallelPlot(whitewine,
             rotateTitle = TRUE,
             histoVisibility = histoVisibility)
```



